'use strict';

/**
 * Session state machine states for KasiConnect order flow.
 *
 * Transitions:
 *   AWAITING_VENDOR_TYPE → AWAITING_ITEMS
 *   AWAITING_ITEMS → AWAITING_CLARIFICATION | AWAITING_CONFIRMATION
 *   AWAITING_CLARIFICATION → AWAITING_ITEMS | AWAITING_CONFIRMATION
 *   AWAITING_CONFIRMATION → AWAITING_FULFILMENT_TYPE (food vendors) | ORDER_PLACED (retail)
 *   AWAITING_FULFILMENT_TYPE → ORDER_PLACED
 *   ORDER_PLACED → (terminal / reset on new order)
 */
const SESSION_STATES = {
  AWAITING_VENDOR_TYPE: 'AWAITING_VENDOR_TYPE',
  AWAITING_ITEMS: 'AWAITING_ITEMS',
  AWAITING_CLARIFICATION: 'AWAITING_CLARIFICATION',
  AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
  AWAITING_FULFILMENT_TYPE: 'AWAITING_FULFILMENT_TYPE',
  ORDER_PLACED: 'ORDER_PLACED',
};

/**
 * Valid state transitions.
 * Maps current state → array of allowed next states.
 */
const VALID_TRANSITIONS = {
  [SESSION_STATES.AWAITING_VENDOR_TYPE]: [SESSION_STATES.AWAITING_ITEMS],
  [SESSION_STATES.AWAITING_ITEMS]: [
    SESSION_STATES.AWAITING_CLARIFICATION,
    SESSION_STATES.AWAITING_CONFIRMATION,
  ],
  [SESSION_STATES.AWAITING_CLARIFICATION]: [
    SESSION_STATES.AWAITING_ITEMS,
    SESSION_STATES.AWAITING_CONFIRMATION,
  ],
  [SESSION_STATES.AWAITING_CONFIRMATION]: [
    SESSION_STATES.AWAITING_FULFILMENT_TYPE,
    SESSION_STATES.ORDER_PLACED,
    SESSION_STATES.AWAITING_ITEMS,
  ],
  [SESSION_STATES.AWAITING_FULFILMENT_TYPE]: [SESSION_STATES.ORDER_PLACED],
  [SESSION_STATES.ORDER_PLACED]: [SESSION_STATES.AWAITING_VENDOR_TYPE],
};

module.exports = { SESSION_STATES, VALID_TRANSITIONS };
