/**
 * Session state machine states for KasiConnect order flow.
 *
 * Transitions:
 *   AWAITING_SECTOR → AWAITING_LOCATION
 *   AWAITING_LOCATION → AWAITING_VENDOR_SELECTION
 *   AWAITING_VENDOR_SELECTION → AWAITING_ITEMS
 *   AWAITING_ITEMS → AWAITING_CLARIFICATION | AWAITING_CONFIRMATION
 *   AWAITING_CLARIFICATION → AWAITING_ITEMS | AWAITING_CONFIRMATION
 *   AWAITING_CONFIRMATION → AWAITING_FULFILMENT_TYPE (food vendors) | AWAITING_VENDOR_RESPONSE (retail)
 *   AWAITING_FULFILMENT_TYPE → AWAITING_VENDOR_RESPONSE
 *   AWAITING_VENDOR_RESPONSE → ORDER_PLACED
 *   ORDER_PLACED → (terminal / reset on new order)
 */
export const SESSION_STATES = {
  AWAITING_SECTOR: 'AWAITING_SECTOR',
  AWAITING_LOCATION: 'AWAITING_LOCATION',
  AWAITING_VENDOR_SELECTION: 'AWAITING_VENDOR_SELECTION',
  AWAITING_ITEMS: 'AWAITING_ITEMS',
  AWAITING_CLARIFICATION: 'AWAITING_CLARIFICATION',
  AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
  AWAITING_FULFILMENT_TYPE: 'AWAITING_FULFILMENT_TYPE',
  AWAITING_VENDOR_RESPONSE: 'AWAITING_VENDOR_RESPONSE',
  ORDER_PLACED: 'ORDER_PLACED',
} as const;

/** Union of all valid session state strings. */
export type SessionState = (typeof SESSION_STATES)[keyof typeof SESSION_STATES];

/**
 * Valid state transitions.
 * Maps current state → array of allowed next states.
 */
export const VALID_TRANSITIONS: Record<SessionState, SessionState[]> = {
  [SESSION_STATES.AWAITING_SECTOR]: [SESSION_STATES.AWAITING_LOCATION],
  [SESSION_STATES.AWAITING_LOCATION]: [SESSION_STATES.AWAITING_VENDOR_SELECTION],
  [SESSION_STATES.AWAITING_VENDOR_SELECTION]: [SESSION_STATES.AWAITING_ITEMS],
  [SESSION_STATES.AWAITING_ITEMS]: [
    SESSION_STATES.AWAITING_CLARIFICATION,
    SESSION_STATES.AWAITING_CONFIRMATION,
  ],
  [SESSION_STATES.AWAITING_CLARIFICATION]: [
    SESSION_STATES.AWAITING_ITEMS,
    SESSION_STATES.AWAITING_CONFIRMATION,
  ],
  [SESSION_STATES.AWAITING_CONFIRMATION]: [
    SESSION_STATES.AWAITING_FULFILMENT_TYPE,
    SESSION_STATES.AWAITING_VENDOR_RESPONSE,
    SESSION_STATES.AWAITING_ITEMS,
  ],
  [SESSION_STATES.AWAITING_FULFILMENT_TYPE]: [SESSION_STATES.AWAITING_VENDOR_RESPONSE],
  [SESSION_STATES.AWAITING_VENDOR_RESPONSE]: [SESSION_STATES.ORDER_PLACED],
  [SESSION_STATES.ORDER_PLACED]: [SESSION_STATES.AWAITING_SECTOR],
};
